config/routes.rb
Rails.application.routes.draw do

  get 'users/index'

  get 'users/new'

  get 'users/edit'

  get 'users/create'

  get 'users/update'

  get 'users/destroy'

  # Semi-static page routes
  get 'home', to: 'home#index', as: :home
  get 'home/about', to: 'home#about', as: :about
  get 'home/contact', to: 'home#contact', as: :contact
  get 'home/privacy', to: 'home#privacy', as: :privacy
  get 'home/search', to: 'home#search', as: :search

  # Authentication routes
  resources :sessions
  resources :users
  get 'users/new', to: 'users#new', as: :signup
  get 'user/edit', to: 'users#edit', as: :edit_current_user
  get 'login', to: 'sessions#new', as: :login
  get 'logout', to: 'sessions#destroy', as: :logout

  # Resource routes (maps HTTP verbs to controller actions automatically):
  resources :owners
  resources :animals
  resources :pets
  resources :visits
  resources :dosages
  resources :treatments
  resources :medicines
  resources :procedures

  # Routes for mecidine and procedure costs
  get 'medicine_costs/new', to: 'medicine_costs#new', as: :new_medicine_cost
  get 'procedure_costs/new', to: 'procedure_costs#new', as: :new_procedure_cost
  post 'medicine_costs', to: 'medicine_costs#create', as: :medicine_costs
  post 'procedure_costs', to: 'procedure_costs#create', as: :procedure_costs

  # Routes for searching
  # get 'medicines/search', to: 'medicines#search', as: :medicine_search
  # get 'owners/search', to: 'owners#search', as: :owner_search
  # get 'pets/search', to: 'pets#search', as: :pet_search

  # You can have the root of your site routed with 'root'
  root 'home#index'
end

app/models/medicine.rb
class Medicine < ApplicationRecord
  
  # Relationships
  has_many :animal_medicines
  has_many :animals, :through => :animal_medicines
  has_many :medicine_costs
  has_many :dosages
  has_many :visits, :through => :dosages

  # Scopes
  scope :alphabetical, -> { order('name') }
  scope :active,       -> { where(active: true) }
  scope :depleted,     -> { where('stock_amount < ?', 100) }
  scope :vaccines,     -> { where(vaccine: true) }
  scope :nonvaccines,  -> { where(vaccine: false) }
  scope :for_animal,   ->(animal_id) { joins(:animal_medicines).where('animal_medicines.animal_id = ?', animal_id) }
  
  # Validations
  validates_presence_of :name
  validates_numericality_of :stock_amount, :only_integer => true, :greater_than_or_equal_to => 0
  
  # Other methods
  # attr_accessor :destroyable

  def is_vaccine?
    vaccine
  end
  
  def current_cost_per_unit
    curr_cost_of_medicine = self.medicine_costs.current
    return nil if curr_cost_of_medicine.empty?
    curr_cost_of_medicine.first.cost_per_unit
  end

  # Callbacks
  # before_destroy :is_destroyable?
  # after_rollback :convert_to_inactive

  # private
  # def is_destroyable?
  #   @destroyable = self.dosages.empty?
  # end

  # def convert_to_inactive
  #   if !destroyable.nil? && destroyable == false
  #     self.update_attribute(:active, false)
  #   end
  #   @destroyable = nil
  # end
end

app/controllers/medicines_controller.rb
class MedicinesController < ApplicationController

  before_action :set_medicine, only: [:show, :edit, :update, :destroy]
  before_action :check_login
  authorize_resource

  def index
    # get all visits in reverse chronological order, 10 per page
    @medicines = Medicine.alphabetical.paginate(page: params[:page]).per_page(10)
  end
  
  def show
    # get the cost history for this medicine
    @prices = @medicine.medicine_costs.chronological #.to_a.reverse
  end
  
  def new
    @medicine = Medicine.new
  end
  
  def create
    @medicine = Medicine.new(medicine_params)
    if @medicine.save
      flash[:notice] = "Successfully added #{@medicine.name}."
      redirect_to @medicine
    else
      render action: 'new'
    end
  end
  
  def edit
  end
  
  def update
    if @medicine.update_attributes(medicine_params)
      flash[:notice] = "Successfully updated #{@medicine.name}."
      redirect_to @medicine
    else
      render action: 'edit'
    end
  end
  
  def destroy
    @medicine.destroy
    flash[:notice] = "Successfully removed #{@medicine.name}."
    redirect_to medicines_url
  end

    private
    # Use callbacks to share common setup or constraints between actions.
    def set_medicine
      @medicine = Medicine.find(params[:id])
    end
    # Never trust parameters from the scary internet, only allow the white list through.
    def medicine_params
      params.require(:medicine).permit(:name, :description, :stock_amount, :admin_method, :unit, :vaccine, :active)
    end
end

    

app/views/medicines/_cost_history.html.erb
<% unless @prices.empty? %>
  <div class="card">
    <div class="card-content">
      <span class="card-title">Cost History</span>
      <table class="striped highlight">
      <thead>
        <th>Date</th>
        <th class="align_right">Cost Per Unit</th>
      </thead>
        <% for price in @prices %>
          <tr>
            <td><%= price.start_date.strftime("%b %d, %Y") %></td>
            <td class="align_right"><%= number_to_currency(price.cost_per_unit/100.0) %></td>
          </tr>
        <% end %>
    </table>
    </div>
    <div class="card-action">
      <%= link_to "Add a new cost", new_medicine_cost_path(medicine_id: @medicine.id) %>
    </div>
  </div>
<% else %>
  <div class="card grey lighten-3">
    <div class="card-action">
      <%= link_to "Add a new cost", new_medicine_cost_path(medicine_id: @medicine.id) %>
    </div>
  </div>
<% end %>

app/views/medicines/_form.html.erb
<%= simple_form_for(@medicine) do |f| %>
  <%= f.error_notification %>
  <div class="row">
    <div class="form-inputs">
      <%= f.input :name, label_html: { class: 'active' } %>
      <%= f.input :description, label_html: { class: 'active' } %>
      <%= f.input :admin_method, collection: ['oral','injection','intravenous','topical'], include_blank: true %>
      <%= f.input :unit, label_html: { class: 'active' } %>
      <%= f.input :stock_amount, label_html: { class: 'active' } %>
      <%= f.input :vaccine, as: :radio_buttons %>
      <%= f.input :active %>
    </div>
  </div>
  <div class="row">
    <div class="form-actions col s8">
      <%= f.button :submit %>
    </div>
  </div>
<% end %>

app/views/medicines/_medicine_data.html.erb
<div class="card">
  <div class="card-content">
    <h5>Information for <%= @medicine.name %></h5><br />

    <b>Description:&nbsp;&nbsp;</b>
      <%= @medicine.description %><br /><br />

    <b>Administer method:&nbsp;&nbsp;</b>
      <%= @medicine.admin_method %><br /><br />

    <b>Amount in stock:&nbsp;&nbsp;</b>
      <%= number_with_delimiter(@medicine.stock_amount) %> <%= @medicine.unit %><br /><br />

    <b>Vaccine?&nbsp;&nbsp;</b>
      <%= @medicine.vaccine ? "Yes" : "No" %><br /><br />

    <b>Currently offered?&nbsp;&nbsp;</b>
      <%= @medicine.active ? "Yes" : "No" %><br><br><br>
  </div>
</div>

app/views/medicines/_medicines_list.html.erb
<h4>Medicines at PATS</h4>

<table class="striped highlight">
  <thead>
    <th>Name</th>
    <th>Stock Amount</th>
    <th>Current Unit Cost</th>
    <th class="align_center">Options</th>
  </thead>
  <% for medicine in @medicines %>
    <tr>
      <td><%= link_to medicine.name, medicine_path(medicine) %></td>
      <td><%= number_with_delimiter(medicine.stock_amount) %> <%= medicine.unit %></td>
      <td class="align_center"><%= medicine.current_cost_per_unit.nil? ? 'N/A' : number_to_currency(medicine.current_cost_per_unit/100.0) %></td>
      <td class="align_center">
      <%= link_to edit_medicine_path(medicine) do %>
            <i class="material-icons">edit</i>
        <% end %>
        &nbsp;&nbsp;&nbsp;&nbsp; 
        <%= link_to(medicine_path(medicine), method: :delete, data: { confirm: 'Are you sure you wish to delete this information?' }) do %>
            <i class="material-icons">delete</i>
        <% end %>
      </td>
    </tr>
  <% end %>
</table>
<br />
<%= will_paginate @medicines, previous_label: "Previous&nbsp;", next_label: "&nbsp;Next" %>
<p>&nbsp;</p>
<%= render :partial => "partials/add_new_object", locals: {model_name: 'medicine'} %>

app/views/medicines/edit.html.erb
<h5>Editing Medicine</h5>

<%= render 'form', medicine: @medicine %>

<p>&nbsp;</p>
<%= link_to 'Show', @medicine %> |
<%= link_to 'Back', medicines_path %>

app/views/medicines/index.html.erb
<%= render partial: "partials/structure1", locals: {model_name: "medicine", 
                                                       primary: "medicines_list", 
                                                       secondary: nil,
                                                       sidebar: "medicine_search"} %>

app/views/medicines/new.html.erb
<h5>New Medicine</h5>

<%= render 'form', medicine: @medicine %>

<p>&nbsp;</p>
<%= link_to 'Back', medicines_path %>

app/views/medicines/show.html.erb
<%= render partial: "partials/structure2", locals: {model_name: "medicine", 
                                                         object: @medicine,
                                                         primary: "medicine_data", 
                                                         secondary: nil,
                                                         sidebar: "cost_history"} %>